#!/bin/bash
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt
#
N=${1}
cat << EOD
template <unsigned long I>
consteval auto reflect() {
    return I;
}

template <unsigned long I>
consteval auto foo() {
    return I;
}
consteval int bar() {
	return static_cast<int>(
EOD
#
for I in $(seq 1 $((N-1)))
do echo "	foo<reflect<$((I))UL>()>()+"
done
#
cat << EOD
	foo<reflect<$((N))UL>()>());
}
int main() {
	return bar();
}
EOD
