#!/bin/bash
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt
#
N=${1}
cat << EOD
template <int I>
struct wrapper { consteval operator int() const { return I;} };

consteval int foo(wrapper<0>) {
    return 0;
}

template <int I>
consteval int foo(wrapper<I>) {
    return foo(wrapper<I-1>{});
}

int main() {
	return foo(wrapper<$((N))>{});
}
EOD
