#!/bin/bash
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt
#
N=${1}
cat << EOD
consteval int foo(int i) {
	if(i == 0) {
	    return 0;
	}
	return foo(i-1);
}

int main() {
	return foo(${N});
}
EOD
