#!/bin/bash
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt

library=${1}
shift
example_src_dir="$(<SOURCE_DIR)/example/${library}"

cd $(dirname ${0})/example/${library} &&
for example
do
	if [[ -f "${example_src_dir}/${example}.cpp" ]]
	then make ${example} && ./${example}
	else echo "Invalid '${library}' example name: '${example}'"
	fi
done
