#!/bin/bash
# Copyright Matus Chochlik.
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt

library=${1}
shift
test_src_dir="$(<SOURCE_DIR)/test/${library}"

cd $(dirname ${0})/test/${library} &&
for test
do
	if [[ -f "${test_src_dir}/${test}.cpp" ]]
	then make ${library}-${test} && ./${library}-${test}
	else echo "Invalid '${library}' test name: '${test}'"
	fi
done
