mirror::program_arg Class Reference
Mirror (0.4.0) a C++ reflection library
mirror::program_arg Class Reference
Utilities
Class representing a single main function (command-line) argument.
#include <mirror/program_args.hpp>
Public Types
using value_type = std::string_view
Alias for the argument value type.
Public Member Functions
constexpr program_arg () noexcept=default
Default constructor.
auto has_value () const noexcept -> bool
Indicates if the arguments has_value.
operator bool () const noexcept
Indicates if the arguments has value.
auto position () const noexcept
Returns the index of this argument.
auto is_first () const noexcept -> bool
Indicates if this is the first command-line argument.
auto is_last () const noexcept -> bool
Indicates if this is the last command-line argument.
auto get () const noexcept -> value_type
Returns the value of this argument if valid, an empty string view otherwise.
operator value_type () const noexcept
Implicit cast to value_type.
auto next () const noexcept -> program_arg
Returns the argument following this one.
auto prev () const noexcept -> program_arg
Returns the argument preceding this one.
auto starts_with (value_type str) const noexcept -> bool
Indicates if the argument starts with str.
auto ends_with (value_type str) const noexcept -> bool
Indicates if the argument ends with str.
auto is_long_tag (value_type str) const noexcept -> bool
Indicates if the argument is "--<str>".
auto operator== (const value_type &v) const noexcept
Indicates if this argument's value is equal to the specified string.
auto operator!= (const value_type &v) const noexcept
Indicates if this argument's value is different than the specified string.
Detailed Description
Class representing a single main function (command-line) argument.
See also
program_args
Note
Do not construct directly. Use program_arguments.
Member Function Documentation
ends_with()
auto mirror::program_arg::ends_with (value_type str) const -> bool inline noexcept
Indicates if the argument ends with str.
See also
get
starts_with
is_long_tag
get()
auto mirror::program_arg::get () const -> value_type inline noexcept
Returns the value of this argument if valid, an empty string view otherwise.
See also
starts_with
ends_with
Referenced by ends_with(), is_long_tag(), operator value_type(), operator!=(), operator==(), and starts_with().
is_long_tag()
auto mirror::program_arg::is_long_tag (value_type str) const -> bool inline noexcept
Indicates if the argument is "--<str>".
See also
get
starts_with
ends_with
next()
auto mirror::program_arg::next () const -> program_arg inline noexcept
Returns the argument following this one.
See also
prev
operator bool()
mirror::program_arg::operator bool () const inline noexcept
Indicates if the arguments has value.
See also
is_valid
operator value_type()
mirror::program_arg::operator value_type () const inline noexcept
Implicit cast to value_type.
See also
get
prev()
auto mirror::program_arg::prev () const -> program_arg inline noexcept
Returns the argument preceding this one.
See also
next
starts_with()
auto mirror::program_arg::starts_with (value_type str) const -> bool inline noexcept
Indicates if the argument starts with str.
See also
get
ends_with
is_long_tag
The documentation for this class was generated from the following file:
mirror/program_args.hpp
Copyright © 2015-2022 Matúš Chochlík.
<chochlik -at -gmail.com>
Documentation generated on Wed Jan 5 2022 by Doxygen (version 1.9.1).