Metaobject sequence operations
Mirror (0.7.0) a C++ reflection library
Metaobject sequence operations
Functions
constexpr auto mirror::unpack (metaobject_sequence auto mo) noexcept
Unpacks a sequence metaobject into sequence of separate metaobject ids.
constexpr auto mirror::make_sequence (metaobject auto...) noexcept
Makes an unpacked_metaobject_sequence from individual metaobjects.
constexpr auto mirror::count_if (metaobject_sequence auto mo, auto predicate) noexcept -> size_t
Counts elements in a metaobject sequence satisfying a predicate.
constexpr auto mirror::transform (metaobject_sequence auto mo, auto function) noexcept
Transforms each element in a sequence by applying the given function.
template<template< typename... > class Container, template< typename > class Transform>
constexpr auto mirror::store_transformed_types (metaobject_sequence auto mo) noexcept -> Container< Transform< unspecified >... >
Unreflects and transforms by Transform and instantiates Container.
template<template< typename > class Transform>
constexpr auto mirror::transform_types (metaobject_sequence auto mo) noexcept -> type_list< Transform< unspecified >... >
Unreflects metaobject in a sequence and transforms by Transform.
constexpr auto mirror::extract_types (metaobject_sequence auto mo) noexcept -> type_list< unspecified... >
Unreflects metaobject in a sequence and stores them in type_list.
constexpr auto mirror::fold (metaobject_sequence auto mo, auto transform, auto aggregate)
Transforms each metaobject in sequence and then aggregates the result.
constexpr auto mirror::join (metaobject_sequence auto mo, auto transform, auto separator, auto aggregate)
Transforms each metaobject in sequence and aggregates them.
constexpr auto mirror::join_to_string (metaobject_sequence auto mo, auto transform, std::string_view separator) -> std::string
Transforms each metaobject and joins the results separated by separator.
constexpr void mirror::for_each (metaobject_sequence auto mo, auto function) noexcept
Calls the specified function for each metaobject in a sequence.
constexpr void mirror::for_each_info (metaobject_sequence auto mo, auto function) noexcept
Calls the specified function for each metaobject in a sequence.
constexpr auto mirror::find_if (metaobject_sequence auto mo, auto predicate) noexcept
Finds first metaobject in sequence satisfying a predicate.
constexpr auto mirror::find_if_not (metaobject_sequence auto mo, auto predicate) noexcept
Finds first metaobject in sequence not satisfying a predicate.
constexpr auto mirror::find_ranking (metaobject_sequence auto mo, auto transform, auto compare)
Finds metaobject with ranking value of some property.
constexpr auto mirror::find_ranking (metaobject_sequence auto mo, auto transform)
Finds metaobject with highest value of some property.
constexpr auto mirror::get_top_value (metaobject_sequence auto mo, auto transform)
Finds the highest value of a property of metaobjects in a sequence.
constexpr auto mirror::filter (metaobject_sequence auto mo, auto predicate) noexcept
Removes metaobjects not satisfying a predicate from a sequence.
constexpr auto mirror::is_sorted (unpacked_metaobject_sequence<>, auto compare) -> bool
Tests if metaobjects in a sequence are sorted according to compare function.
constexpr auto mirror::all_of (metaobject_sequence auto mo, auto predicate) noexcept -> bool
Indicates if all metaobjects in a sequence satisfy a predicate.
constexpr auto mirror::any_of (metaobject_sequence auto mo, auto predicate) noexcept -> bool
Indicates if some metaobjects in a sequence satisfy a predicate.
constexpr auto mirror::none_of (metaobject_sequence auto mo, auto predicate) noexcept -> bool
Indicates if no metaobjects in a sequence satisfy a predicate.
Detailed Description
Function Documentation
all_of()
constexpr auto mirror::all_of (metaobject_sequence auto mo, auto predicate) -> bool constexpr noexcept
Indicates if all metaobjects in a sequence satisfy a predicate.
See also
filter
any_of
none_of
any_of()
constexpr auto mirror::any_of (metaobject_sequence auto mo, auto predicate) -> bool constexpr noexcept
Indicates if some metaobjects in a sequence satisfy a predicate.
See also
filter
all_of
none_of
count_if()
constexpr auto mirror::count_if (metaobject_sequence auto mo, auto predicate) -> size_t constexpr noexcept
Counts elements in a metaobject sequence satisfying a predicate.
See also
find_if
find_if_not
extract_types()
constexpr auto mirror::extract_types (metaobject_sequence auto mo) -> type_list< unspecified... > constexpr noexcept
Unreflects metaobject in a sequence and stores them in type_list.
See also
transform
store_transformed_types
transform_types
for_each
fold
This function takes a sequence of metaobjects reflecting types, un-reflects them, applies the Transform template on each one and then instantiates the type_list template with the resulting types.
Examples
mirror/has_padding.cpp.
filter()
constexpr auto mirror::filter (metaobject_sequence auto mo, auto predicate) constexpr noexcept
Removes metaobjects not satisfying a predicate from a sequence.
Removes metaobjects satisfying a predicate from a sequence.
See also
remove_if
for_each
select
filter
for_each
select
find_if()
constexpr auto mirror::find_if (metaobject_sequence auto mo, auto predicate) constexpr noexcept
Finds first metaobject in sequence satisfying a predicate.
See also
find_if_not
find_ranking
for_each
count_if
find_if_not()
constexpr auto mirror::find_if_not (metaobject_sequence auto mo, auto predicate) constexpr noexcept
Finds first metaobject in sequence not satisfying a predicate.
See also
find_if
find_ranking
for_each
count_if
find_ranking() [1/2]
constexpr auto mirror::find_ranking (metaobject_sequence auto mo, auto transform) constexpr
Finds metaobject with highest value of some property.
See also
find_if
find_if_not
for_each
get_top_value
This function extracts the value of a property for each metaobjects is a sequence and returns the metaobject for which the value is highest according to a less than operator.
find_ranking() [2/2]
constexpr auto mirror::find_ranking (metaobject_sequence auto mo, auto transform, auto compare) constexpr
Finds metaobject with ranking value of some property.
See also
find_if
find_if_not
for_each
get_top_value
This function extracts the value of a property for each metaobjects is a sequence and returns the metaobject for which the value is highest according to a binary compare function.
fold()
constexpr auto mirror::fold (metaobject_sequence auto mo, auto transform, auto aggregate) constexpr
Transforms each metaobject in sequence and then aggregates the result.
See also
transform
transform_types
for_each
join
This function takes a sequence of metaobjects applies the specified transform function on each one of them and then makes a single call to the (variadic) aggregate function with the transformed metaobjects as arguments and returns the aggregated result.
for_each()
constexpr void mirror::for_each (metaobject_sequence auto mo, auto function) constexpr noexcept
Calls the specified function for each metaobject in a sequence.
See also
transform
fold
join
Examples
mirror/fake_rpc.cpp, mirror/filter.cpp, mirror/gen_puml_diagram.cpp, mirror/group_by.cpp, mirror/next_weekday.cpp, mirror/print_enumerators.cpp, mirror/print_op_results.cpp, mirror/print_traits.cpp, mirror/remove_if.cpp, mirror/repeat_message_args.cpp, mirror/row_polymorphism.cpp, and mirror/sort_by.cpp.
Referenced by mirror::for_each_info(), mirror::for_each_metaobject_operation(), and mirror::get_traits().
for_each_info()
constexpr void mirror::for_each_info (metaobject_sequence auto mo, auto function) constexpr noexcept
Calls the specified function for each metaobject in a sequence.
See also
for_each
for_each_iteration_info
transform
fold
join
This function call the provided function for each metaobject in a sequence where the first argument is the metaobject and the second is an instance of for_each_iteration_info providing information about each cycle.
Examples
mirror/print_struct.cpp.
get_top_value()
constexpr auto mirror::get_top_value (metaobject_sequence auto mo, auto transform) constexpr
Finds the highest value of a property of metaobjects in a sequence.
See also
find_ranking
is_sorted
for_each
This function extracts the value of a property for each metaobjects is a sequence and returns that value which is highest according to a binary compare function.
is_sorted()
constexpr auto mirror::is_sorted (unpacked_metaobject_sequence<> , auto compare) -> bool constexpr
Tests if metaobjects in a sequence are sorted according to compare function.
See also
find_ranking
get_top_value
join()
constexpr auto mirror::join (metaobject_sequence auto mo, auto transform, auto separator, auto aggregate) constexpr
Transforms each metaobject in sequence and aggregates them.
See also
transform
transform_types
for_each
fold
join_to_string()
constexpr auto mirror::join_to_string (metaobject_sequence auto mo, auto transform, std::string_view separator) -> std::string constexpr
Transforms each metaobject and joins the results separated by separator.
See also
transform
for_each
join
Examples
mirror/overload_arity.cpp, and mirror/remove_if.cpp.
make_sequence()
constexpr auto mirror::make_sequence (metaobject auto...) constexpr noexcept
Makes an unpacked_metaobject_sequence from individual metaobjects.
See also
is_object_sequence
none_of()
constexpr auto mirror::none_of (metaobject_sequence auto mo, auto predicate) -> bool constexpr noexcept
Indicates if no metaobjects in a sequence satisfy a predicate.
See also
filter
all_of
none_of
store_transformed_types()
template<template< typename... > class Container, template< typename > class Transform> constexpr auto mirror::store_transformed_types (metaobject_sequence auto mo) -> Container< Transform< unspecified >... > constexpr noexcept
Unreflects and transforms by Transform and instantiates Container.
See also
transform
transform_types
for_each
fold
This function takes a sequence of metaobjects reflecting types, un-reflects them, applies the Transform template on each one and then instantiates the Container template with the resulting types.
transform()
constexpr auto mirror::transform (metaobject_sequence auto mo, auto function) constexpr noexcept
Transforms each element in a sequence by applying the given function.
See also
transform_types
for_each
fold
Examples
mirror/fake_rpc.cpp, mirror/find_if.cpp, mirror/has_padding.cpp, and mirror/print_op_results.cpp.
transform_types()
template<template< typename > class Transform> constexpr auto mirror::transform_types (metaobject_sequence auto mo) -> type_list< Transform< unspecified >... > constexpr noexcept
Unreflects metaobject in a sequence and transforms by Transform.
See also
transform
store_transformed_types
extract_types
for_each
fold
This function takes a sequence of metaobjects reflecting types, un-reflects them, applies the Transform template on each one and then instantiates the type_list template with the resulting types.
unpack()
constexpr auto mirror::unpack (metaobject_sequence auto mo) constexpr noexcept
Unpacks a sequence metaobject into sequence of separate metaobject ids.
See also
reflects_object_sequence
Referenced by mirror::for_each_info().
Copyright © 2015-2022 Mat Chochlk.
<chochlik -at -gmail.com>
Documentation generated on Sat Feb 12 2022 by Doxygen (version 1.9.1).