Utilities
Mirror (0.8.0) a C++ reflection library
Utilities
Classes
class for_each_iteration_info
Class used to provide information about sequence element iteration.
struct type_list< T >
Represents a list of types. Unlike tuple does not store values.
class interface< Derived >
Base template for abstract interfaces, implements common functionality.
class abstract< Derived >
Base template for polymorphic classes, implements common functionality.
struct indeterminate_t
Type of the indeterminate constant assignable to tribool.
class weakbool
Weak tri-state boolean value.
class tribool
Tri-state boolean value.
class bitfield< Bit >
Class for manipulating and testing a group of enumeration-based bits.
class puml_class_diagram
Class that can generate PlantUML code for entities reflected by metaobjects.
class program_arg
Class representing a single main function (command-line) argument.
class url
Class parsing and providing access to parts of a URL.
Typedefs
template<typename T >
using extracted_type_t = std::remove_cv_t< typename extracted_traits< std::remove_cv_t< std::remove_reference_t< T > >>::value_type >
Returns the value type of an extractable.
Functions
void add_to (chaiscript::ChaiScript &chai, metaobject_sequence auto mos)
Registers the entities reflected by metaobjects with a ChaiScript engine.
template<typename E >
auto enum_to_string (E e) noexcept -> string_view
Returns the name of the specified enumerator.
template<typename E >
auto string_to_enum (string_view s) noexcept -> std::optional< E >
Finds the value of enum type E with the specified name.
template<typename T >
auto from_string (const std::string_view src) noexcept -> extractable
Converts the string representation in src to a value of type T.
template<typename T >
auto from_extractable_string (const extractable auto src, std::type_identity< T > tid={}) noexcept -> std::optional< T >
Converts the extractable string in src to a value of type T.
constexpr auto operator&& (const tribool a, const tribool b) noexcept
Tri-state boolean and operator.
constexpr auto operator|| (const tribool a, const tribool b) noexcept
Tri-state boolean or operator.
constexpr auto has_value (extractable auto p) noexcept -> bool
Indicates if an extractable has a valid value.
constexpr auto extract (extractable auto p) noexcept -> const auto &
Extracts a value from an extractable if it has value.
template<typename V >
consteval auto has_value_type (const extractable auto &v) noexcept -> bool
Indicates in an extractable has value type of V.
template<typename Dst , typename Src >
static constexpr auto is_within_limits (const Src value) noexcept
Indicates if value fits into the specified Dst type.
template<typename Dst , typename Src >
static constexpr auto limit_cast (Src value) noexcept -> std::enable_if_t< std::is_convertible_v< Src, Dst >, Dst >
Casts value to Dst type if the value fits in that type.
template<typename Src >
static constexpr auto signedness_cast (Src value) noexcept
Casts value to a type with the opposite signedness.
template<typename Dst , typename Src >
static constexpr auto convert_if_fits (Src value) noexcept -> std::enable_if_t< std::is_convertible_v< Src, Dst >, std::optional< Dst >>
Optionally converts value to Dst type if the value fits in that type.
Variables
static constexpr const indeterminate_t indeterminate
Constant representing unspecified tribool value.
template<typename X >
concept extractable
Concept constraining extractable types.
Detailed Description
Typedef Documentation
extracted_type_t
using extracted_type_t = std::remove_cv_t<typename extracted_traits< std::remove_cv_t<std::remove_reference_t<T> >>::value_type>
Returns the value type of an extractable.
See also
extract
Function Documentation
convert_if_fits()
static constexpr auto mirror::convert_if_fits (Src value) -> std::enable_if_t<std::is_convertible_v<Src, Dst>, std::optional<Dst>> static constexpr noexcept
Optionally converts value to Dst type if the value fits in that type.
See also
is_within_limits
limit_cast
from_string
enum_to_string()
auto enum_to_string (E e) -> string_view noexcept
Returns the name of the specified enumerator.
See also
string_to_enum
Examples
mirror/enum_min_max.cpp, mirror/next_weekday.cpp, reflexpr/enum_to_string.cpp, and reflexpr/enum_to_string_map.cpp.
extract()
constexpr auto mirror::extract (extractable auto p) -> const auto & constexpr noexcept
Extracts a value from an extractable if it has value.
See also
has_value The extractable p must have a valid value, otherwise the behavior is undefined.
from_extractable_string()
auto from_extractable_string (const extractable auto src, std::type_identity< T > tid = {}) -> std::optional<T> noexcept
Converts the extractable string in src to a value of type T.
See also
from_string
is_within_limits
convert_if_fits
from_string()
auto from_string (const std::string_view src) -> extractable noexcept
Converts the string representation in src to a value of type T.
See also
from_extractable_string
is_within_limits
convert_if_fits
Referenced by mirror::convert_if_fits(), mirror::limit_cast(), and mirror::signedness_cast().
has_value()
constexpr auto mirror::has_value (extractable auto p) -> bool constexpr noexcept
Indicates if an extractable has a valid value.
See also
extract
has_value_type()
consteval auto has_value_type (const extractable auto & v) -> bool noexcept
Indicates in an extractable has value type of V.
See also
extract
extracted_type_t
is_within_limits()
static constexpr auto mirror::is_within_limits (const Src value) static constexpr noexcept
Indicates if value fits into the specified Dst type.
See also
limit_cast
convert_if_fits
This function tests if the specified argument would fit into another type. For example if a value stored in 64-bit integer can be converted into a 16-bit integer without overflow.
limit_cast()
static constexpr auto mirror::limit_cast (Src value) -> std::enable_if_t<std::is_convertible_v<Src, Dst>, Dst> static constexpr noexcept
Casts value to Dst type if the value fits in that type.
See also
is_within_limits
convert_if_fits
signedness_cast
Precondition
is_within_limits<Dst>(value)
signedness_cast()
static constexpr auto mirror::signedness_cast (Src value) static constexpr noexcept
Casts value to a type with the opposite signedness.
See also
is_within_limits
convert_if_fits
limit_cast
string_to_enum()
auto string_to_enum (string_view s) -> std::optional<E> noexcept
Finds the value of enum type E with the specified name.
See also
enum_to_string
Examples
reflexpr/string_to_enum.cpp.
Variable Documentation
extractable
concept extractable
Concept constraining extractable types.
See also
has_value
extract This is a concept for types that can optionally store and/or provide access to a value. Examples of extractable types are pointers, smart pointers, optionals, etc.
Copyright © 2015-2022 Matúš Chochlík.
<chochlik -at -gmail.com>
Documentation generated on Wed Mar 2 2022 by Doxygen (version 1.9.1).